<a href="https://colab.research.google.com/github/imdeja/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/Jake_Dennis_LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The values taken in.
### Hidden Layer: Any layer in between the input and the output.
### Output Layer: The values computed per given input.
### Neuron: Any individual output cell or node in a neural network.
### Weight: A number multplied to an input.
### Activation Function: A transfer function that decides how much signal to transfer to the next level.
### Node Map: A diagram of the node connectivity.
### Perceptron: A neural network with a single node.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

##### Begin with the inputs. To compute every node in the following layer, the inputs are multiplied by a weight. Those weights are added, and a predisposition variable is additionally included. Next an actuation function is applied. The outcome is the output.


## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [2]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [3]:
list(df)

['x1', 'x2', 'y']

In [0]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [0]:
import numpy as np
inputs = np.array(df[["x1","x2"]])

inputs = np.append(inputs, [[1],[1],[1],[1]],axis = 1)

correct_outputs = np.array(df[["y"]])

In [7]:
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [8]:
correct_outputs

array([[1],
       [1],
       [1],
       [0]])

In [9]:
weights = (2 * np.random.random((3,1)) - 1)
weights

array([[-0.49794234],
       [ 0.71029203],
       [-0.39696617]])

In [10]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-0.39696617],
       [-0.89490851],
       [ 0.31332586],
       [-0.18461648]])

In [11]:
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.40204147],
       [0.29009792],
       [0.57769686],
       [0.45397652]])

In [12]:
correct_outputs

array([[1],
       [1],
       [1],
       [0]])

In [13]:
error = correct_outputs - activated_outputs
error

array([[ 0.59795853],
       [ 0.70990208],
       [ 0.42230314],
       [-0.45397652]])

In [14]:
adjustments = error * sigmoid_derivative(weighted_sum)
adjustments

array([[ 0.1437517 ],
       [ 0.14619803],
       [ 0.10302643],
       [-0.11253254]])

In [15]:
weights += np.dot(inputs.T, adjustments)
weights

array([[-0.46427685],
       [ 0.70078592],
       [-0.11652255]])

In [16]:
for iteration in range(1000):
    weighted_sum = np.dot(inputs, weights)
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)    

Weights after training
[[-5.4767155 ]
 [-5.47671548]
 [ 8.30777736]]
Output after training
[[0.99975304]
 [0.94430086]
 [0.94430086]
 [0.06629405]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [17]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [18]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

target = ['Outcome']
feats = list(diabetes)[:-1]
X = diabetes[feats]
y = np.array(diabetes[target])

scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [0]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1+ np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1 - sx)   

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        # Add bias var
        bias = []
        for i in range(len(X)):
            bias += [[1]]
        X = np.append(X, bias,axis = 1)
        
        # Randomly Initialize Weights
        self.weights = (2 * np.random.random((X.shape[1], 1)) - 1)
        
        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights)
            # Activate!
            activated_output = sigmoid_derivative(weighted_sum)
            # Cac error
            error = y - activated_output
            # Update the Weights
            adjustments = error * sigmoid_derivative(weighted_sum)
            self.weights += np.dot(X.T, adjustments)
        return self 

    def activate(self, X):
        """Calculate net input"""
        # Add bias var
        bias = []
        for i in range(len(X)):
            bias += [[1]]
        X = np.append(X, bias,axis = 1)
        
        weighted_sum = np.dot(X, self.weights)
        activated_output = sigmoid(weighted_sum)
        return activated_output
    
    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.activate(X) >= .5, 1, 0)

In [0]:
pn = Perceptron()

In [21]:
pn.fit(X, y)

In [0]:
pn.weights
pn.activate(X)

In [0]:
pn.predict(X)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?